filename = "text.txt"
users_filename = "users.json"
revisions_filename = "revisions.json"
sorted_revisions_filename = "revisions_sorted.csv"
categories_filename = "categories.json"
categories_wikitext_filename = "categories_wikitext.json"
